### ISSUE TITLE
Firefox mobile browser problem

### ISSUE THREAD

**Issue by adamus007p** [thirtybees/stripe#10]
I was testing with different phones, android and iphones.
The problem is with javascript and fields.
In firefox I need to use a “space” to have a exp date as 12/19
In other case there is 1219 / which give an error.

I am not sure about card numbers but I can put
4242 4242 4242 4242 424 i my opinion there are 3 extra numbers to much for the limit.
I though that card numbers have only 16 digits.
That problems are only with Firefox on mobile phone.
Please install firefox on you mobile and check it by yourself.
Do not use a mobile version on Chrome or any PC emulators, just a phone.

To assume to many characters for card number, it should be a limit up to 16characters
Problem with exp date. 1219 /
not 12 / 19
Problem occurs only on Firefox mobile browser on mobile phones, not PC.

on Firefox PC browser everything works
on Chrome PC browser everything works
on Firefox mobile browser problems
on Chrome mobile browser everything works

on Firefox mobile browser I can use space and enter exp date using enter and pay, but it is no user friendly as also nobody know about it.

2nd thing
Why I am able to add 19 numbers
4242 4242 4242 4242 424??

max should be 4242 4242 4242 4242 >> 16 numbers

**Comment by firstred** [comment]
Hi,
That's because the Visa's range can be either 13, 16 or 19 digits: https://en.wikipedia.org/wiki/Payment_card_number

If you have any further questions about the card's JS, you can get your answers here: https://github.com/jessepollak/card

We are not the author of the card input.

**Comment by adamus007p** [comment]
what about Firefox mobile browser? have you check it on your side?
