### ISSUE TITLE
Class 'ThirtybeesStripe\Source' not found

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/stripe#11]
I get the error 
_Class 'ThirtybeesStripe\Source' not found
at line 111 in file modules/stripe/controllers/front/validation.php_

I updated from 1.4.3 to 1.4.4 but that made no difference
![stripe](https://user-images.githubusercontent.com/13930107/34227332-0e660a62-e5cd-11e7-84b8-7e083f2a4b3d.jpg)

**Comment by firstred** [comment]
Gotcha! I have immediately updated the module. Thanks!
