### ISSUE TITLE
500 server error - validation of payment

### ISSUE THREAD

**Issue by adamus007p** [thirtybees/stripe#12]
During module/stripe/validation

I am receiving 500 server error. Payment are delivered but there are error regards 3d secure.

The problem exist where I have a debit card with 3d secure, but I am not using enforce 3d secure.

**Comment by firstred** [comment]
https://github.com/thirtybees/stripe/blob/master/controllers/front/validation.php#L117

Could it be this line?

I can't see the error message from here, 500 is pretty generic. If you have an error message, please share it here.

**Comment by adamus007p** [comment]
it was a generic error. I don't have this error.
That's right this line make problem.

I have changed to:

        try {
            $defaultCard = \ThirtyBeesStripe\Source::retrieve($stripeCustomer->default_source);
        } catch (Exception $e) {
            $defaultCard = new stdClass();
        }

        /** @var \ThirtyBeesStripe\Card $defaultCard */

**Comment by firstred** [comment]
Ahh great, one step closer. Note that a few changes have been pushed. You
can try those as well.

**Comment by adamus007p** [comment]
I am not sure it only this line make a problem. I think also in other lines. Basically that exceptions.

**Comment by firstred** [comment]
Got it, it has been changed. Thanks!

**Comment by adamus007p** [comment]
my solution:

if (Configuration::get(Stripe::THREEDSECURE) && $defaultCard->three_d_secure !== 'not_supported' || $defaultCard->three_d_secure === 'required') {
+        if (Configuration::get(Stripe::THREEDSECURE) && property_exists($defaultCard,'three_d_secure') && $defaultCard->three_d_secure !== 'not_supported' || $defaultCard->three_d_secure === 'required') {
