### ISSUE TITLE
emails confirmations after the purchase

### ISSUE THREAD

**Issue by adamus007p** [thirtybees/stripe#13]
I am not receiving email confirmations for merchant, when customer order a product.
It was happened after the module update. From some old version to the newest version.

**Comment by firstred** [comment]
Still having this problem? I just did a couple of checks and it sent all the emails.
It is not even possible to influence this from the module because the emails are sent after the order validation. I think you will have to solve it by configuring the order status (Orders > Statuses). It will need to be a validating status and have an email template. Those are the requirements for thirty bees to send out emails.

**Comment by adamus007p** [comment]
To confirm if we are talking about the same thing. Me as a merchant I was receiving emails from Stripe after the payment. Emails like that:
![image](https://user-images.githubusercontent.com/19956106/35344729-1e2d2094-012e-11e8-81dc-4dc63dd41997.png)


In email source Received: from mail-p2.stripe.com ([166.78.69.60])

so it was emails from stripe.com not from the shop.

After the update I am not receiving any emails.


In orders when I will click view I can see payments accepted.

**Comment by firstred** [comment]
This is something you can configure on this page: https://dashboard.stripe.com/settings/user
Make sure you use the the API keys that belong to the account for which you are configuring the notifications.

**Comment by adamus007p** [comment]
Hi Michael, you are right.
but

The last email we sent you was returned by your mail server. If you entered the wrong address, you can fix it below. If you've solved the problem with your email provider, we can mark your email address as valid.

click

We've removed your email from our block list, and we'll resume sending your regular emails. If we get another returned email, we'll let you know on your dashboard.


I did not noticed it and I would not expect.
Maybe it was when the server was down.


Just confirmed and emails works again.


I put this info here maybe it will be helpful for someone :)
