### ISSUE TITLE
naming Credit Card

### ISSUE THREAD

**Issue by adamus007p** [thirtybees/stripe#14]
I would add in FO not pay by Credit Card

but but Debit/Credit Card

as customers are not aware about debit and credit cards. They can think I can't pay because I have not credit card.

BO:

default new payments are called as Credit Card it would be better Stripe as stripe offer not only Credit Card payments > better filtering.

**Comment by firstred** [comment]
Hi, thanks for opening this issue.

Are you aware that every string in the module can be translated? If you visit Localization > Translations you can update the texts.

**Comment by adamus007p** [comment]
I have done it. I was thinking for other less advanced users.

**Comment by firstred** [comment]
Then we probably have to make translations easier. That really should be the only way to edit translations.
