### ISSUE TITLE
feature request: add payment methods

### ISSUE THREAD

**Issue by adamus007p** [thirtybees/stripe#15]
I am not sure where to add a feature requests.

I would like to ask to add a Polish payment methods and German SEPA transfers.

Please move/close if this is a wrong place.

**Comment by firstred** [comment]
Maybe in the future. They are not freely available right now.

**Comment by adamus007p** [comment]
OK, I can help with real tests in both methods.

> They are not freely available right now.
What you mean?

**Comment by firstred** [comment]
Are you part of the private beta?

**Comment by adamus007p** [comment]
Yes
Przelewy24 (Private Beta) Live
SEPA Direct Debit Testmode >> need to activate it

**Comment by firstred** [comment]
Good news, Przelewy24 has just been added!

SEPA Direct Debit will have to wait until we have added support for recurring payments to the module.

**Comment by adamus007p** [comment]
Super :)

Recurring payments would be great.

**Comment by firstred** [comment]
Closing this item. P24 has been added. SEPA has been placed on the roadmap, so no need to discuss any further.
