### ISSUE TITLE
After 1.6 upgrade it will no longer allow both test and live keys.

### ISSUE THREAD

**Issue by zapps12** [thirtybees/stripe#17]
I tried uninstalling and reinstalling the module but it will not allow both test and live keys to be added at same time.

The only thing that saves is the test keys, so in order to even get the live keys to show up under live, I need to put them in test, and then it saves them under the live lines.

Was working perfectly until upgrade, and the previous version still works as normal.

**Comment by firstred** [comment]
I suggest you remove all module files, upload the 1.6 binary and try again. I can't reproduce it here...

**Comment by firstred** [comment]
I forgot to say there's no need to uninstall the module first. Just removing the folder `/modules/stripe` then uploading the zip via your back office should be sufficient to refresh all files.

**Comment by zapps12** [comment]
Thanks for your response.
I deleted the /modules/stripe folder and re-uploaded the zip but unfortunately I am still experiencing the same issue.
I haven't tested live mode but the test mode works so I *think* the module is still technically working on the front-end. I am not positive but I believe the only problem is not being able to insert both keys at once.
If you're sure there's no problem on the module end I can have my developer look at it but the old version does have the same issue for me.

**Comment by firstred** [comment]
Managed to reproduce it on my end. There is a problem in the module. The update to 1.6.1 should solve it.

**Comment by firstred** [comment]
Sorry that it took so long to figure this out.

**Comment by zapps12** [comment]
Awesome.
I'll try the new version out later today.
Thank you for fixing it.

**Comment by bhtoys** [comment]
I'm on 1.7 and the site won't allow any payments at all. When I click it, it bounces back to the order page.
