### ISSUE TITLE
feature requst - send email after failed paymet method

### ISSUE THREAD

**Issue by adamus007p** [thirtybees/stripe#18]
I think that good idea would be email to merchant and to customer where there is problem with customer card. Eg. insufficient funds. That info is during error, but good idea would be email to customer account this error and/or next step.

I have notice that sometimes customer is not able to buy via stripe but via paypal (debit card) is able to pay.

For that errors it would be possible to sent email with info what to do, try reorder and try use different payment methods or contact with your bank + e.g translations.

Manual contact can save failed orders, automatic contact would be much more easier.

**Comment by firstred** [comment]
This would be beyond the scope of this module. We're committed to making payment gateway integrations and make them work well, but email automation is not on our roadmap. 

Fortunately you can still implement this feature. When you enable Stripe's webhooks you can then write a couple of scripts that subscribe to the events and send emails accordingly. Hope that helps!

**Comment by adamus007p** [comment]
Any idea how the script could look like?

Basically after error on stripe payment I want to sent to customer this error and info what customer need to do.
