### ISSUE TITLE
can't set currency

### ISSUE THREAD

**Issue by zimmer-media** [thirtybees/stripe#19]
I did the module update a few days ago. Now I do not receive any orders or payments via Stripe.

I have already uninstalled and reinstalled the module. Unfortunately, it still did not help.
Now I noticed in the settings of the payment methods that I no longer have a radio button or check box in the Currencies section. For the sections Groups, Countries and Delivery Services I can see and select the checkboxes.

you can see full message here
https://forum.thirtybees.com/topic/1619/stripe-bug-can-t-set-currency

**Comment by zimmer-media** [comment]
![grafik](https://user-images.githubusercontent.com/14238489/38057063-86639742-32de-11e8-8a29-95cf146e85c0.png)

**Comment by firstred** [comment]
Looks more like a core bug since modules can't influence the way this page is displayed.
