### ISSUE TITLE
Add 3D Secure (version 2.0)

### ISSUE THREAD

**Issue by adamus007p** [thirtybees/stripe#21]
Ask for new feature:
add 3D Secure (version 2.0)

 There is a news from Stripe:

Strong Customer Authentication is a new European regulation coming into effect on September 14, 2019, which will require additional authentication for many online payments.

You can learn more about SCA and the latest regulatory requirements in our guide, or in our upcoming webinar on March 27, 2019.

Read our guide to learn more about what to expect from SCA

March 19, 2019

source:

https://stripe.com/blog/strong-customer-authentication-mar-2019

 

https://stripe.com/guides/strong-customer-authentication 

https://www.barclaycard.co.uk/business/news-and-insights/guide-to-strong-customer-authentication
VISA and MasterCard will be mandating that the new version of 3D Secure (version 2.0) should be in place for issuers and merchants by April 2019 in preparation for the mass adoption in September 2019.

https://forum.thirtybees.com/topic/2743-strong-customer-authentication-sca/

**Comment by getdatakick** [comment]
Since version 1.7.0 stripe module supports SCA
