### ISSUE TITLE
Error message in GuzzleClient.php: localization, relevancy and ux

### ISSUE THREAD

**Issue by romaric17** [thirtybees/stripe#24]
Hi

3 suggestions for classes/GuzzleClient.php

The error message has to be localized so it can be translated in TB.

Moreover when the credit card number is wrong (wrong CVV for instance) we get the error "Could not connect with Stripe" but it is not relevant. Stripe is actually responding and throwing the card number error, so we should give a better error message to the user.

Last suggestion: can we get the error message INSIDE the checkout iframe instead of getting a whole page with just the error message. That way the user would stay on the checkout page and try again without having to go back to the cart. Conversion :)))

**Comment by adamus007p** [comment]
I would add https://stripe.com/docs/recipes/sending-emails-for-failed-payments for merchants and to increase ROI.

**Comment by getdatakick** [comment]
This was implemented as part of 1.7.0
