### ISSUE TITLE
CRITICAL: Since update - no payments taken: "failed to create stripe review object" on mobile and returns to cart on desktop

### ISSUE THREAD

**Issue by gingerling** [thirtybees/stripe#28]
Hi Since updating for the new SCA measures, I have had no payments come through

I checked and found that on desktop, when you submit payment you are returned back to the first step in the cart process.

https://youtu.be/1Fcb1rRkwAk

On mobile you get an error "Failed to create stripe review object"

![Screenshot_20190904-122258_Firefox](https://user-images.githubusercontent.com/2853040/64251641-e3d00d00-cf10-11e9-8bd1-c5df2b00952a.jpg)

To try and fix I reviewed my settings and double checked my api keys, it's all fine. I noticed that stripe still recognises if the wrong card details are put in, so it's not completable broken.

Please can you help ASAP, I'm losing money

**Comment by gingerling** [comment]
![Screenshot from 2019-09-04 12-59-53](https://user-images.githubusercontent.com/2853040/64252870-eed86c80-cf13-11e9-8ac6-7f0c927faa44.png)

Also I see this, when I try and view stripe transactions - maybe it's related

**Comment by gingerling** [comment]
I tried to reinstall it, now it won't show up and I have a 500 error when I go to Modules > Payment

![Screenshot from 2019-09-04 13-13-42](https://user-images.githubusercontent.com/2853040/64253779-e8e38b00-cf15-11e9-98ef-c10786b467a6.png)

**Comment by Traumflug** [comment]
@gingerling, did you try to find out what's asked here?

https://forum.thirtybees.com/topic/2743-strong-customer-authentication-sca/?do=findComment&comment=30167

**Comment by gingerling** [comment]
Ok, I've tried, first it made a table in swedish and I got errors on modules > Payment thing

![Screenshot from 2019-09-04 20-27-31](https://user-images.githubusercontent.com/2853040/64285675-e1db6d80-cf53-11e9-905a-d8e3ab2e6857.png)

So I deleted that and tried to make it manually, but it was too complicated, and now the query wont run again, it says there is a syntax error.

Don't really know what I am doing tbh, this is all over my head

**Comment by gingerling** [comment]
hmmm, got it now - got email instructions from the guy who made the plugin, and it worked better

"the most probable culprit is missing table tb_stripe_review (you might use different prefix than tb_)

Please check in your database that the table exists. You can use this sql query:

show create table tb_stripe_review;

If the table exists, it should display something like this:

CREATE TABLE `tb_stripe_review` (
  `id_stripe_review` int(11) NOT NULL AUTO_INCREMENT,
  `id_order` int(11) unsigned NOT NULL,
  `status` int(11) unsigned NOT NULL DEFAULT '0',
  `id_review` varchar(255) DEFAULT NULL,
  `id_payment_intent` varchar(255) DEFAULT NULL,
  `id_charge` varchar(255) DEFAULT NULL,
  `captured` tinyint(1) DEFAULT NULL,
  `test` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id_stripe_review`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

please check that the result is the same. If not, let me know.

If the result of the *show table* query is something like this: Table 'ps17.tb_stripe_reviews' doesn't exist
then you need to create it. The easiest way is to copy and paste the whole CREATE TABLE statement above.

"

**Comment by gingerling** [comment]
There is an issue though as my table prefix seems to be PS still - it allowed the stripe module to work but I still got the error: "failed to create stripe review object"

**Comment by gingerling** [comment]
Now I corrected that, the module works and I see the normal options under module > pagments but I still get the error 

 An error occurred:

    Failed to create stripe review object


I then noticed that there were some tables with ps1_ as the prefix so I made the table with that too, but I still have the error

![Screenshot from 2019-09-04 20-59-29](https://user-images.githubusercontent.com/2853040/64287224-09800500-cf57-11e9-9472-014798285e94.png)

I suppose technically this is different to before as before, on desktop it just refreshed the cart, but now it has the same error as mobile.

**Comment by getdatakick** [comment]
It's different. Now it complains about stripe transaction object. So rinse and repeat, this time it's `<PREFIX>_stripe_transaction` table that's missing or corrupted:

```sql
CREATE TABLE `tb_stripe_transaction` (
  `id_stripe_transaction` int(11) NOT NULL AUTO_INCREMENT,
  `id_order` int(11) unsigned NOT NULL DEFAULT '0',
  `type` int(11) unsigned NOT NULL DEFAULT '0',
  `source` int(11) unsigned NOT NULL DEFAULT '0',
  `card_last_digits` int(4) unsigned DEFAULT '0',
  `id_charge` varchar(128) NOT NULL,
  `amount` int(11) unsigned DEFAULT '0',
  `date_add` datetime DEFAULT NULL,
  `date_upd` datetime DEFAULT NULL,
  `source_type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_stripe_transaction`)
)
```

**Comment by Traumflug** [comment]
Looking at the left column of the screenshot above, your database prefix is neither `ps_` nor `tb_`, but `ps1_`.

**Comment by gingerling** [comment]
Hi, I have both ps1 and ps prefixes (don't know why)

![Screenshot from 2019-09-05 12-06-57](https://user-images.githubusercontent.com/2853040/64336861-eba5b500-cfd5-11e9-9197-f6c48a0f28fd.png)

![Screenshot from 2019-09-05 12-06-46](https://user-images.githubusercontent.com/2853040/64336872-f3fdf000-cfd5-11e9-9606-4bddfaaf5ee6.png)

I wrote this in a comment last night but must not have submitted it or something.

I did the next step by @getdatakick (well spotted that the error is in fact totally different! I missed that).

I ran it with ps_ and that didn't work, so I ran it with ps1_ and that seems to be working
![Screenshot from 2019-09-05 12-14-29](https://user-images.githubusercontent.com/2853040/64337275-ed23ad00-cfd6-11e9-9804-87d797cfc7d5.png)

![Screenshot from 2019-09-05 12-15-25](https://user-images.githubusercontent.com/2853040/64337281-f0b73400-cfd6-11e9-9c06-def5fbbb54b9.png)

**Comment by gingerling** [comment]
HOWEVER, there is a really super serious issue - it looks like when the error message was showing, the payments were still being taken by stripe but no order was being recorded by TB. 

I put together the data from tb and stripe to try and build a picture of it. I spoke with my bank to eliminate my test payments, and that leaves me with 3 amounts of money paid from unidentified people and possibly one customer who managed to place an order without being charged (I'm going to have to look into that more to understand it).

![Screenshot from 2019-09-05 12-41-24](https://user-images.githubusercontent.com/2853040/64338840-93bd7d00-cfda-11e9-9492-c2e12f86bde1.png)

I am going to have to try and find these customers via abandoned carts and explain to them the situation. This is obviously quick a tricky issue, I'm not sure if anything can be done to stop this happening to others? We were lucky, one customer called about the card payment failing, otherwise I would not have known about this issue and it could have gone on longer (I am also a small store so don't get many orders)

**Comment by gingerling** [comment]
Found two of the three missing orders in abandoned carts, matching the amount in stripe, so that's okay. The third order dosen't match the cart though, so need to talk to the customer I think it is (based on timestamp). 

It's worth noting (for anyone else going through this) that the abandoned carts don't match the amount's exactly because they don't include shipping - so you need to look at other factors such as date & time and customer name if that is stated in stripe. Also, the stripe name is the card-holder which doesn't always match the account name (e.g. if wife pays and uses husbands TB account) so you may need to call the customer to check. 

I have emailed the customer for the order when I can't find any payment, will see what they say and hopefully get paid another way, if it's missing.

**Comment by gingerling** [comment]
ps: There has been an 18 month delay in the SCA implementation, so this update could be withdrawn to allow further testing

https://internetretailing.net/themes/themes/uks-fca-delays-psd2-sca-deadline-to-secure-payments--good-or-bad-news-for-consumers-and-retailers-20068

**Comment by getdatakick** [comment]
The tables `<PREFIX>_stripe_review` and `<PREFIX>_stripe_transaction` were introduced in previous version(s) of this module. For example, `stripe_transaction` table was already present in version [1.1.0](https://github.com/thirtybees/stripe/blob/de53a8372e2418beed4b638844b7c3b68181b51a/upgrade/upgrade-1.1.0.php#L26), and `stripe_review` was introduced in version [1.6.0](https://github.com/thirtybees/stripe/blob/de53a8372e2418beed4b638844b7c3b68181b51a/upgrade/upgrade-1.6.0.php#L33). The last version only [added 2 more columns](https://github.com/thirtybees/stripe/blob/de53a8372e2418beed4b638844b7c3b68181b51a/upgrade/upgrade-1.7.0.php#L32) to table `stripe_review`.

However, in your case, these tables were completely missing. I don't know how this happened, but it definitely wasn't caused by the new version. Most of the people who upgraded didn't encounter any problems or issues.

**Comment by gingerling** [comment]
OK. I am quite a new user of the module, I have only had it up and running since 8th July and taken 70 payments. I don't believe I have ever updated the stripe plug-in before this latest update. My site was transitioned from prestashop to thirtybees about 2 years ago.

Anyway, lets keep eyes peeled and make sure more folks don't have the issue - it sounds like it would be hard to get to the bottom of it. Thanks so much for your help and work on this plugin, it's a relief to be up to date with secularity x

**Comment by gingerling** [comment]
Hi, I'm still having issues with this plugin, my sales are about half their normal level. Customers report that once they fill in their card details and click pay, it sends them back to the cart page. It's not affecting every customer.. I'm unavailable at the moment, I will try and hand this bug to my sysadmin.

**Comment by gingerling** [comment]
Had another issue today, a guy paid for his order, he has it showing as pending in his bank account, but it's not showing on our stripe or on TB. Any chance this is an issue with stripe itself? I'll call them in the morning, but I'm getting to the point where I'm going to need to change to a different system. It really sucks because stripe as being great otherwise.

**Comment by Dh42** [comment]
If it is showing pending in his account and it is not reporting the payment on your stripe dashboard, that is for sure a problem on stripe's side.

**Comment by gingerling** [comment]
Ok, summary of ongoing issue:

Since 1st September stripe shows 79 payments, 38 went through, 38 are "pending", 3 are failed/refunded. The "pending" sales total £1716.83. 

Stripe customer service said: "You thought this started when you upgraded for SCA, and I can confirm that this is the case. 

It seems that there was never a card added to that payment request to be charged. Your developer needs to make sure you have the integration set up correctly so that you are collecting card info and passing it along with the payment intent"

As far as I can tell everything is set up fine, it's maddening that it's 50% of payments failing, not 100% - I would have noticed this sooner.

**Comment by gingerling** [comment]
It will take me  a while to get all this data straight, but it looks like we have shipped most of these orders - so we received and order in TB but the payment never finished in stripe. We will hopefully be able to recover some of the money as our customers are good folk.

**Comment by getdatakick** [comment]
Payment intents are, well, intents. They are not charges. They represent a payment session. And some of these sessions are completed, and some of them are abandoned. That's totally valid.

What happens:

1) Your customer enters your checkout page
2) Thirtybees check if some active Payment Intent exists. If not, it uses stripe api to create new one and associate this customer/cart with it. At this moment, we don't necessarily know much about customer. If customer is logged out, we don't even know email address. Let alone card number.
3) Customer is supposed to complete checkout. If he does, the payment intent will be amended with customer info + payment info (card number,...). But customer can decide not to complete the payment and leave the checkout page.  In that case, Payment Intent in stripe still exists and is valid for another few hours.

So, overall, this all doesn't mean that 50% of payments are failing. It means that 50% of your customer doesn't finish the checkout flow. That's very different metric

**Comment by gingerling** [comment]
right, but this is what my stripe looks like before the plugin upgrade:

![Screenshot from 2019-10-07 16-21-15](https://user-images.githubusercontent.com/2853040/66325199-bd8dfa80-e91e-11e9-979d-c3e5abb1e726.png)

This is it after:

![Screenshot from 2019-10-07 16-21-40](https://user-images.githubusercontent.com/2853040/66325223-c5e63580-e91e-11e9-85b1-c9444b8ecffb.png)

Are you saying this change is not down to the plugin update but something else?
I thought perhaps it was caused by the additional security features but there don't seem to be any in place yet, at lease from my bank.

**Comment by gingerling** [comment]
just to be clear - these are not abandoned carts, these people are submitting a payment to stripe and getting an error of some kind (can't replicate, plus it flashes up to quick for them to screenshot)

**Comment by adamus007p** [comment]
Hello,
on my end i have checked there is no emails ( i have opened separate issue)
2nd thing is that on mobile when i write card numbers and then write expiry date it jump to top so i need to scroll down to see which numbers I type.

**Comment by adamus007p** [comment]
Hi I can confirm that I have the same problems with newset stripe version.

Any solution to this problem?

**Comment by adamus007p** [comment]
So, overall, this all doesn't mean that 50% of payments are failing. It means that 50% of your customer doesn't finish the checkout flow. That's very different metric


my test  show that 1enty is incomplete where second one in the same time it is completed.

it is like it put every time double information. It make no sense.

**Comment by getdatakick** [comment]
If you have enabled multiple stripe payments options (say stripe checkout and payment request button), then yes -- each have its own session, thus it's own ID. 

How does it affect you?

**Comment by adamus007p** [comment]
There is a mess, there is a lot of entries and sending a lot of data to stripe.
GDPR in EU do not allow it. Stripe see all payments. Maybe some customers do not want to use American payment gateway and prefer local payments.

Now when i pay i see 1 payment finished and on the same time 2nd incomplete.
It make no sense.

Is it possible to change it?

**Comment by adamus007p** [comment]
OK I know what is the problem.

First: there are two types of possible payment.

1.  stripe checkout - it transfer to stripe website and you need to type all card details + addres
in my case there is no copied address there.
Test show me all info email adress etc.

2. Payment using a form on merchant page.
Here we have a form on our shop
![image](https://user-images.githubusercontent.com/19956106/68961088-c8676500-07d1-11ea-99c5-c0806e5d55b6.png)

Here we put only credit/debit card number and pay. There is no needs to add address.

In this method i have no email.

@getdatakick have you check this method too?


Where I have two options on there is two sessions, so why 1payment is completed and 2nd is not completed.


But anyway I am not sure if stripe should send automatically all data to stripe.

**Comment by gingerling** [comment]
> There is a mess, there is a lot of entries and sending a lot of data to stripe.
> GDPR in EU do not allow it. Stripe see all payments. Maybe some customers do not want to use American payment gateway and prefer local payments.
> 
> Now when i pay i see 1 payment finished and on the same time 2nd incomplete.
> It make no sense.
> 
> Is it possible to change it?

Hi, this situation is still ongoing, data is being sent to stripe all the time that should not be there.

**Comment by getdatakick** [comment]
It would be very hard to implement. The reason is strictly technical. 

In order to display card form we need to provide client secret. Client secret is extracted from payment intent object. This means that in order to display card form on checkout page, we need to create PaymentIntent object --> call stripe via server api.

**Comment by adamus007p** [comment]
Here even when you will add anything to card it will be send to stripe.
Even when someone want to use local payment.

When you will add a product you can see it on stripe dashboard.

In US the privacy law is very weak, when in some EU countries is very strict.

Add extra step or page where stripe will be activated.
