### ISSUE TITLE
Code/Script related to stripe in csv when downloading orders (since update)

### ISSUE THREAD

**Issue by gingerling** [thirtybees/stripe#29]
When I download a csv of orders using the export function on **Orders** > **Orders** page, the csv has code in it. The code shows in the reference number column, e.g:
```
data-tooltip="title" |  
-- | --
title="Captured" |  
style="white-space: nowrap | >    Stripe: Credit Card <i class="icon icon-lock"></i>  </span><script type="text/javascript" data-cookieconsent="necessary">  (function () {    function initTooltip() {      if (typeof $ === 'undefined') {        setTimeout(initTooltip, 100);        return;      }      $('#stripe-stat-3693').tooltip();    }    initTooltip();  }());</script>
```

And the the column Payment which used to say "Credit Card" (or "paypal")

```
<span id="stripe-stat-3693
--
```
![Screenshot from 2019-10-05 12-38-23](https://user-images.githubusercontent.com/2853040/66254434-2b46f480-e76e-11e9-8ef8-f74e2808ad65.png)

![Screenshot from 2019-10-05 12-39-07](https://user-images.githubusercontent.com/2853040/66254438-37cb4d00-e76e-11e9-91a5-3726a9079c37.png)

**Comment by getdatakick** [comment]
Fixed by 8e8a879556a28c8f9f2deeb18e03d6ac96ca348d
