### ISSUE TITLE
undefined index source type on line 781

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/stripe#3]
When I press "Stripe transactions" I get a warning window with notices.
![stripe](https://user-images.githubusercontent.com/13930107/32136357-9cac0708-bc0c-11e7-8d2f-f2c2673b65a3.jpg)

I am using the latest version (1.4.2).

**Comment by firstred** [comment]
Probably missed an update (1.1.0). You can execute these queries manually to fix it:
```sql
ALTER TABLE `PREFIX_stripe_transaction` ADD `source_type` VARCHAR(255) NULL;
UPDATE TABLE `PREFIX_stripe_transaction` SET `source_type` = 'cc';
```
(Replace `PREFIX_` with your own).

I have a feeling this update failed on several instances with MySQL 5.7+/MariaDB 10.2. I'll push a hotfix (1.4.3) with the same update script if the column is missing. Make sure you update it ASAP as you cannot accept sources (3D secure, iDEAL, etc.) without this column.

**Comment by musicpanda** [comment]
Thanks. That seems to fix it.

Just a slight correction for the code above for other people with the same problem as the above code is not correct. It should be "UPDATE" instead of "UPDATE TABLE":
`ALTER TABLE `PREFIX_stripe_transaction` ADD `source_type` VARCHAR(255) NULL;
UPDATE `PREFIX_stripe_transaction` SET `source_type` = 'cc';`

**Comment by firstred** [comment]
Indeed. Fixed it :)

You can quote with two backticks instead `` ` `` and keep a space on the left AND right, like this:
``` `` ALTER TABLE `PREFIX_stripe_transaction` ADD `source_type` VARCHAR(255) NULL; `` ```
it results in
`` ALTER TABLE `PREFIX_stripe_transaction` ADD `source_type` VARCHAR(255) NULL; ``

What I used above is an SQL code block:
````
```sql
ALTER TABLE `PREFIX_stripe_transaction` ADD `source_type` VARCHAR(255) NULL;
UPDATE `PREFIX_stripe_transaction` SET `source_type` = 'cc';
```
````
