### ISSUE TITLE
SSL CA bundle not found

### ISSUE THREAD

**Issue by adamus007p** [thirtybees/stripe#30]
Hello I have similar issue to:
https://github.com/guzzle/guzzle/issues/1807

My error is:

Fatal error: Uncaught Stripe\Error\ApiConnection: Could not connect with Stripe: InvalidArgumentException: SSL CA bundle not found: /home/myshopdomain2/domains/myshopdomain.com/tools/cacert.pem in /home/myshopdomain2/domains/myshopdomain.com/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:337 Stack trace: #0 /home/myshopdomain2/domains/myshopdomain.com/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(43): GuzzleHttp\Handler\CurlFactory->applyHandlerOptions(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /home/myshopdomain2/domains/myshopdomain.com/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(39): GuzzleHttp\Handler\CurlFactory->create(Object(GuzzleHttp\Psr7\Request), Array) #2 /home/myshopdomain2/domains/myshopdomain.com/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #3 /home/myshopdomain2/domains/myshopdomain.com/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object in /home/myshopdomain2/domains/myshopdomain.com/modules/stripe/classes/GuzzleClient.php on line 245

**Comment by getdatakick** [comment]
You need to fix your thirtybees installation. Obviously, the `/tools/cacert.pem` file is missing, or is not readable. You can use core updater to do that, or you can download this file from [github](https://github.com/thirtybees/thirtybees/blob/1.1.x/tools/cacert.pem)
