### ISSUE TITLE
mobile jump problem

### ISSUE THREAD

**Issue by adamus007p** [thirtybees/stripe#32]
Hello,
The tthing is that on mobile when i write card numbers and then write expiry date it jump to top so i need to scroll down to see which numbers I type.
On PC is ok, On mobile Android9 there is jumping.

Do you have the same problems?

**Comment by getdatakick** [comment]
The payment widget is provided and maintained by stripe, there's nothing we can do to fix it. If it behaves incorrectly, please file an issue on stripe

**Comment by adamus007p** [comment]
Problem is only with mobile version of Firefox, Chrome mobile is OK.

**Comment by adamus007p** [comment]
Firefox responsive emulator on PC is ok, so only one way is to test on real phone browser not emulators.

When there is bigger pane with number it jump every time when i type.

**Comment by adamus007p** [comment]
First: there are two types of possible payment.

    stripe checkout - it transfer to stripe website and you need to type all card details + addres
    in my case there is no copied address there.
    Test show me all info email adress etc.

    Payment using a form on merchant page.
    Here we have a form on our shop
    image

Here we put only credit/debit card number and pay. There is no needs to add address.

In this method i have no email.

@getdatakick have you check this method too?



The problem on Firefox mobile is only when the form is enabled.


1. Enable Stripe credit card form - jumping
2. Enable Stripe credit card form + Enable Stripe Checkout   - jumping
3. Enable Stripe Checkout  - no jumping
