### ISSUE TITLE
If post code is not entered customer sent back to cart page with no error

### ISSUE THREAD

**Issue by gingerling** [thirtybees/stripe#35]
I have had complaints about customers trying to pay and getting sent back to the cart page. Most of the customers were not especially helpful in describing it so I have had help from @ksimunovic working out the issue.

It seems that if a customer does not put in their postcode, they are sent back to the cart with no error message. I suspect people are not yet used to putting in this kind of information as the requirement is new, so they just ignore it.

Anyway, here is a video:

https://greencloud.gn.apc.org/index.php/s/P9zXo2mzYmQMXYs

Suggest a pop up error or stay on the page and have an error saying "postcode is mandatory" or similar.

Thanks!

**Comment by vduarte06** [comment]
I noticed the same problem  in my website

**Comment by gingerling** [comment]
Hi any chance of a fix for this soon?

**Comment by CoiledString** [comment]
This really is a pain for me. I'm considering removing stripe until it's resolved as it's causing a lot of confusion for customers and they are not completing checkouts. 

Anyone suggest a fix other my current ugly *Important information* banner that nobody pays any attention to?

**Comment by getdatakick** [comment]
Workaround: don't use embedded credit card form. By using redirect to stripe checkout, this UX glitch will not be present. 

Also, it's important to note that redirect to stripe page is preferable from other points of view as well:

- embedded CC form is not SCA-ready. With SCA being mandatory in most EU countries the payments made through form would be declined.
- PCI compliance -- by collecting credit card information on your website you are required to be PCI compliant.

**Comment by CoiledString** [comment]
Ah okay, I've done that now as I'm not 100% PCI compliant. 
Thanks for the quick response!

**Comment by gingerling** [comment]
Stripe is PCI compliant by the fault even on your website though right? I
thought that was the point of stripe?

**Comment by getdatakick** [comment]
You are correct, new stripe.js is indeed SAQ-A compatible. Older versions of stripe forms required SAQ-A-EP, that's where my confusion come from.
