### ISSUE TITLE
Sofort not showing up

### ISSUE THREAD

**Issue by M4ketech** [thirtybees/stripe#36]
![kuva](https://user-images.githubusercontent.com/8841448/76910551-fa3f2400-68b6-11ea-80b3-49dd0d5ce055.png)

Accept Sofort is enabled at backend.

**Comment by M4ketech** [comment]
![kuva](https://user-images.githubusercontent.com/8841448/76910784-a2ed8380-68b7-11ea-99cd-abe49830a471.png)

**Comment by adamus007p** [comment]
Hi @M4ketech are you this option enabled on you Stripe side?
or on module side?

**Comment by M4ketech** [comment]
That is enabled Stipe side and Module side.

**Comment by adamus007p** [comment]
on shop side what is the country of the customer?

can you change address of the customer to other country like US, UK and check it ?

**Comment by M4ketech** [comment]
I did test with German address and details, still nothing. Let me check again

**Comment by M4ketech** [comment]
![kuva](https://user-images.githubusercontent.com/8841448/76994979-d67fea80-6957-11ea-82d0-dab6df6bdeb3.png)

When using German address: Schiffahrter Damm 3-5, 48145 Münster, German. Hmm Stripe page shows Finnish language, so im not sure is there some detection built in Stripe.

**Comment by M4ketech** [comment]
Using VPN and USA location, still same:
![kuva](https://user-images.githubusercontent.com/8841448/76995569-b7358d00-6958-11ea-989f-bf8abcea2991.png)

**Comment by adamus007p** [comment]
Sofort it is a German Payment method. Try use German address.

Please send screen from your module (stripe)

Please uncheck save, check save and in the end click clear cache in performance tab.

**Comment by adamus007p** [comment]
in https://dashboard.stripe.com/settings/payments 

do you have the same like me LIVE?

![image](https://user-images.githubusercontent.com/19956106/77004041-bbfd3f80-695e-11ea-8995-7ef2d6f6a46a.png)

**Comment by adamus007p** [comment]
Austria, Gernamy Belgium

**Comment by M4ketech** [comment]
![kuva](https://user-images.githubusercontent.com/8841448/77019967-e238d480-698a-11ea-9178-8e56bc932db7.png)

**Comment by M4ketech** [comment]
![kuva](https://user-images.githubusercontent.com/8841448/77020207-96d2f600-698b-11ea-90c3-cb2adf00963d.png)

**Comment by M4ketech** [comment]
I already did try German address, still nothing.

Saving, clearing cache, chaning settings does nothing. Its shows always the default card payment form.

**Comment by M4ketech** [comment]
And since im unable to fast test does Stripe checkout work with other languages, someone else maybe can help me with this, site is live at https://arcticaspenstudio.com

**Comment by adamus007p** [comment]
Please send me a full screen from your Stripe module.

You have no option which should be on.


You have a gateway.

**Comment by adamus007p** [comment]
There are two ways how stripe act.

1. all transaction is redirected on stripe side. 
2. stripe will be visible on your shop.

or both.

It seems that you have only 1st method on.


Show me all your stipe config on scree so I will tell you more.

When you change something remember to use clear cache.

**Comment by M4ketech** [comment]
![kuva](https://user-images.githubusercontent.com/8841448/77109451-9a6a8980-6a2c-11ea-8634-ea9f8cad6aca.png)

**Comment by M4ketech** [comment]
![kuva](https://user-images.githubusercontent.com/8841448/77109484-a8200f00-6a2c-11ea-8c26-9819d2b2b764.png)

**Comment by M4ketech** [comment]
![kuva](https://user-images.githubusercontent.com/8841448/77109497-b110e080-6a2c-11ea-9298-f106c9d318c0.png)

**Comment by M4ketech** [comment]
![kuva](https://user-images.githubusercontent.com/8841448/77109525-bb32df00-6a2c-11ea-936a-05b06f62296f.png)

**Comment by M4ketech** [comment]
![kuva](https://user-images.githubusercontent.com/8841448/77109552-c4bc4700-6a2c-11ea-8e0e-8e0e00c399f2.png)

**Comment by adamus007p** [comment]
enable it

![image](https://user-images.githubusercontent.com/19956106/77121565-c2adb480-6a3b-11ea-9f7a-d3115edf7e5c.png)


and check now

**Comment by M4ketech** [comment]
still nope

![kuva](https://user-images.githubusercontent.com/8841448/77123822-e1b34300-6a49-11ea-9ff2-50639f435556.png)

**Comment by M4ketech** [comment]
https://store.thirtybees.com/shop-modules/payment/stripe-module shows "Last Update: 03/19/2020" hmm so i dont know, its still 1.7.0 version what i already have @getdatakick can you say about that?

**Comment by adamus007p** [comment]
@M4ketech can you turn on all options?
![image](https://user-images.githubusercontent.com/19956106/77128254-bd5a6500-6a4f-11ea-9e05-2936a106fec8.png)



Last thing what I have noticed at my module that there is some bug on Firefox, so please check it also on Chrome.

**Comment by adamus007p** [comment]
![image](https://user-images.githubusercontent.com/19956106/77128578-e4656680-6a50-11ea-9b4a-71abf1682488.png)

**Comment by M4ketech** [comment]
Enabling all shows Alipay, Giropay, Bancontact and iDEAL at checkout. Sofort is still missing.

On Mobile device i see weird purple "osta nyt" what seems like going to google pay

**Comment by adamus007p** [comment]
no sofort, I have check even with German IP. Germany and Austria shipping address.
there is some bug,

**Comment by adamus007p** [comment]
turn on debugging and see if there will be any info

**Comment by adamus007p** [comment]
More interesting are errors on Stripe payment gateway

![image](https://user-images.githubusercontent.com/19956106/77128858-11664900-6a52-11ea-94a7-36905f2eed38.png)

**Comment by adamus007p** [comment]
The final question have you ever this payments method or no.

I had, but I have change this and that or this is a first time of using stripe.

**Comment by M4ketech** [comment]
Im been using Stripe with Wordpress + Woocommerce and with Prestashop before.

**Comment by adamus007p** [comment]
on github there is no updates
https://github.com/thirtybees/stripe/releases
https://github.com/thirtybees/stripe
stripe-v1.7.0.zip << the newest


Had you sofort payment there?

**Comment by adamus007p** [comment]
Did you migrate from Wordpress and Woocommerce to Thirtybees? Why?

**Comment by M4ketech** [comment]
Hmm im not sure, that was 2017-2018. I can see:

Content Security Policy: Site settings prevented the resource from being downloaded from inline ("script-src"). 3 onloadwff.js:71:803622

**Comment by adamus007p** [comment]
Check your logs and debugging
https://forum.thirtybees.com/topic/2452-free-module-advdebug-enable-debug-mode-per-user/
https://docs.thirtybees.com/merchants-guide/advanced-parameters/

**Comment by adamus007p** [comment]
Where you see it? Send a screen.

**Comment by adamus007p** [comment]
Check server logs, if there is any errors or/and check that debugging mode from above.

**Comment by M4ketech** [comment]
![kuva](https://user-images.githubusercontent.com/8841448/77129533-0533b900-6a5d-11ea-91a7-e17695b43b95.png)

**Comment by getdatakick** [comment]
Sofort is correctly displayed if following conditions are met:

- **sofort** is enabled in back office
- **account country**  (not customer address country) is one of `['AT', 'DE', 'NL', 'BE', 'ES']`
- **currency** is EUR

![image](https://github.com/thirtybees/stripe/assets/34651851/2d970b3a-019a-4bfc-bdc8-fc9d5d246f4a)
