### ISSUE TITLE
extra entries in modules directory

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/stripe#4]
When I look in my modules directory I see the following:
![stripe3](https://user-images.githubusercontent.com/13930107/32141916-35e29566-bc8c-11e7-96b4-8e8575e859dd.jpg)
Very likely the file date is the date when I installed the Stripe module.

**Comment by firstred** [comment]
I think it's an updater issue. Can you move it to https://github.com/thirtybees/tbupdater please?

**Comment by musicpanda** [comment]
Are you sure about that? All the directory dates are from the time of the installation. My updates yesterday and today did not leave a trace.

**Comment by firstred** [comment]
Yes
