### ISSUE TITLE
Trying to get property 'value' of non-object

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/stripe#40]
In a production shop I get this error:

PHP Notice:  Trying to get property 'value' of non-object in [...]/cache/smarty/compile/7b/18/eb/7b18eb327394393c82d9140391937cf244a58ae6_0.file.payment.tpl.php on line 60

This line 60 is the translation of https://github.com/thirtybees/stripe/blob/master/views/templates/hook/payment.tpl#L46, which uses `$stripe_session_id`.

This variable was introduced in https://github.com/thirtybees/stripe/commit/fcca3d9b23786ccf911e10c43deeea7d0933f1b7#diff-cd90dbe463f72bd4004254491fa5ea89R46. The same commit introduced code for defining this variable in `hookDisplayPaymentTop()`: https://github.com/thirtybees/stripe/commit/fcca3d9b23786ccf911e10c43deeea7d0933f1b7#diff-42f4aceebe563f60bce9f7939b1c6ef2R2388-R2394

However, `hookDisplayPaymentTop()` renders _views/templates/front/assets.tpl_, which does not use this Smarty variable. This variable is used by _payment.tpl_, which is rendered by `hookPayment()` (via _allpayments.tpl_), which does not define this new variable. This doesn't make sense and leads to the error shown above.

It looks like code for defining `$stripe_session_id` should get moved from `hookDisplayPaymentTop()` to `hookPayment()`, but for the time being that's only a guess.

**Comment by getdatakick** [comment]
Fixed in new vesion
