### ISSUE TITLE
Checkout Error = bouncing to new page?

### ISSUE THREAD

**Issue by bhtoys** [thirtybees/stripe#41]
I'm trying to complete a shop for a not-for profit organization. 
While attempting to checkout, in test mode (and not in test mode), the site bounces me to previous page, or, to the top of the page... 

Can someone please take a look and LMK what's up?

**Comment by getdatakick** [comment]
Looks like you have entered wrong key -- your javascript console says this:

Uncaught IntegrationError: You should not use your secret key with Stripe.js. Please pass a publishable key instead.

**Comment by bhtoys** [comment]
I copied and paste what it gives me. I’ve attached a video of the error it’s doing.

**Comment by bhtoys** [comment]
Update:
All keys are verified. Test keys work. Live Keys do not. 

Local TV is reporting on the charity event on Thursday morning.  Any help you could give would be greatly greatly appreciated. Did a post on thirtybees as well.
