### ISSUE TITLE
Wrong country for Przelewy24

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/stripe#44]
{if ($stripe_p24 && in_array($stripe_country, ['NL'])  && in_array($stripe_currency, Stripe::$methodCurrencies['p24']))}

P24 (Przelewy24) is a Polish payment operator. Country "PL", not "NL".

**Comment by getdatakick** [comment]
Fixed by efc7e60911b9806cabcfa31883468866f17a2222
