### ISSUE TITLE
Stripe Payment Gateway

### ISSUE THREAD

**Issue by BARDAINTL** [thirtybees/stripe#49]
Is anyone else having issues with the credit card 💳  fields populating on the Stripe payment gateway on the website as presented on the preview on the dashboard. Everything is translating perfectly except the Actual entry fields for the Credit Card number. I have tried resetting and reconfiguring &it still
L isn't populating. The issue is not with the Stripe API Keys because all the attempts including the canceled payments are showing up on the Stripe payment accounting tab on the Stripe website. So this must be a bug in the system.  Who has the answer to getting around this bug. And for the record yes we eve n changed the font color thinking that maybe that was the issue. That maybe it was there but just not showing up. Help please with the Thirtybees Stripe Block Shopping cart bug issue.

**Comment by BARDAINTL** [comment]
Here is a video.
The preview for the Credit Card form is showing the home page for the
website. When someone tries to checkout instead of the Credit Card form
coming up, it just loops back to the website when the payment button is
pressed on the shopping cart.

**Comment by getdatakick** [comment]
I don't see any video. Please attach it to github page directly, or upload it somewhere and post link to it
