### ISSUE TITLE
Can this warning be prevented?

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/stripe#5]
I activated Alipay on Stripe.com and I also immediately enabled it on my webshop. Stupid, I know: I should have waited for acceptance first. Anyway, what happened next astonished me. The customer gets a warning whenever he enters the checkout page (so he doesn't need to choose Alipay first). But I do not get a warning in the backoffice. 

Is there something that can be done about this?
![stripe4](https://user-images.githubusercontent.com/13930107/32162288-bd2db6be-bd58-11e7-8770-729aa3e72c60.jpg)

**Comment by firstred** [comment]
Yes, checking your Stripe dashboard.

**Comment by musicpanda** [comment]
I am not sure whether I was clear enough. What annoys me is that a warning that is meant for me as shop owner is shown to my customers. That is a broader problem than my present issue alone. It harms the trust of my customers and it might even involve some security risks.
