### ISSUE TITLE
enforce 3d secure

### ISSUE THREAD

**Issue by adamus007p** [thirtybees/stripe#6]
With newest version enforce 3d secure is not working properly.

Without enforcing 3d secure everything works ok.

Interesting is for me that I was testing with my real debit card which support 3d secure, but during the order I have no 3d secure option. In my case I am received a SMS with code to put on the website.

Maybe add some info or hide this option (enforce 3d secure)?

**Comment by firstred** [comment]
I'll adjust the text. You cannot force the Stripe checkout to use 3D secure. This is for the credit card form only.

**Comment by adamus007p** [comment]
The problem is for all types of cards, debit and credit cards.
Without enforcing 3d secure everything works ok.

**Comment by firstred** [comment]
I think you might have to check this with Stripe. For some reason it redirects without applying 3D secure, but I cannot see what is happening on Stripe's side.
