### ISSUE TITLE
Various errors in 1.8.0

### ISSUE THREAD

**Issue by hank** [thirtybees/stripe#65]
The following line broke using the 1.8.0 commit (stripe.php:193):

```Stripe\Stripe::setAppInfo('thirty bees', $this->version, 'https://thirtybees.com/');```

I changed it to this and it worked:

```\Stripe\Stripe::setAppInfo('thirty bees', $this->version, 'https://thirtybees.com/');```

Once I did that, I received an error at this line, stripe.php:32:

```require_once __DIR__.'/vendor/autoload.php';```

Perhaps this file is missing?

**Comment by getdatakick** [comment]
Did you install dependencies using composer?

**Comment by hank** [comment]
Just figured out the composer issue, trying again now!

**Comment by hank** [comment]
Still getting "Class "Stripe\Stripe" not found" at stripe.php:193. Any advice?

**Comment by getdatakick** [comment]
No idea. Works fine on my local environment, and on my production and demo servers.

Could be opcache issue -- try clearing cache / restarting php server.
 
Also, try to install official zip file from https://github.com/thirtybees/stripe/releases

**Comment by hank** [comment]
OK Thanks for that zip tip, it worked, and I'm very close. In testing in my cart I get "no template found for module stripe" but it was working before with my quick API version hack on 1.7.1. Not sure where to go from here...

**Comment by getdatakick** [comment]
This looks like some sort of caching issues. I recommend you uninstall the module, delete it completely, and then install it from fresh content.

Between every step, go to Advanced Parameters > Performance and clear cache.

**Comment by hank** [comment]
Just followed your advice and it worked this time. Thanks! Funny how I was hacking 1.7.1 to work at the exact same time your were doing 1.8!

**Comment by getdatakick** [comment]
I'm happy to hear that. Yes, it was funny coincidence. I've pushed and few seconds later I received an email that you proposed the PR.

Thanks for the PR anyway, It's very nice to see when people contribute to the project.
