### ISSUE TITLE
Hook actionAdminOrdersListingFieldsModifier

### ISSUE THREAD

**Issue by e-com-presta** [thirtybees/stripe#67]
Order list ornaments added with javascript spoil order list exported to CSV.

**Comment by getdatakick** [comment]
Any idea how to solve this? The data returned by hook are already html tags

**Comment by e-com-presta** [comment]
And this functionality on this hook is needed for something?

**Comment by getdatakick** [comment]
This is generic problem of thirty bees core -- html content should not make it to CSV export. I have created new bug for this.

I have no idea what this custom stripe column is good for. Probably for people using manual capture, so they can quickly determine which orders requires their attention.
