### ISSUE TITLE
500 error when using full refund button

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/stripe#68]
Select full refund button from back office module throws a 500 error and does not switch order status correctly and thus does not affect inventory as it should. Did not update full amount of refund in store either. It does push correct refund amount to stripe. Had to close out with a partial refund as shown in screen shot.

![image](https://github.com/thirtybees/stripe/assets/44684415/2021f7a2-2630-4aec-8e41-207025574f0a)

**Comment by getdatakick** [comment]
I can't reproduce this problem, on my testing account I'm able to use full refund without any errors. Order status is switched correctly, etc.

Please look into your error logs and find out error message for that 500 error code, so we can pinpoint the origin of this problem (It might be issue with different component of the system)
