### ISSUE TITLE
Ideal no longer works

### ISSUE THREAD

**Issue by musicpanda** [thirtybees/stripe#69]
iDeal used to work for me. I received several payments with it. But now when you click on iDeal as payment option you get on a page where the space that used to contain payment information is empty.

![stripe](https://github.com/thirtybees/stripe/assets/13930107/b8f8353f-5cd7-43ea-8171-6c33afceeaef)

I updated the Stripe module to the latest version (1.8.1) but that makes no difference.

**Comment by getdatakick** [comment]
Thanks for bug report. Fixed in version 1.8.2
