### ISSUE TITLE
Stripe module : apparent issue with multistore ?

### ISSUE THREAD

**Issue by DXXS** [thirtybees/stripe#70]
After upgrading to the latest stripe module (1.8.2, TB1.3), I am having an issue wherein when I choose 'Stripe  Pay by Credit Card', my main store still seems to work [redirecting the next page to stripe itself], but other stores just come up with a page within my store that has a ~button saying 'pay with stripe' which doesn't go anywhere.  I don't recall ever having seen this before upgrading.

**Comment by getdatakick** [comment]
I can't reproduce this behavior.

Do you have any javascript errors on your page?

**Comment by DXXS** [comment]
Although turning on Debug & Profiling internally doesn't show anything, in switching on the Javascript Console, yes, there do appear to be some listed:

[Error] SyntaxError: Unexpected token '<'
	(anonymous function) (eupayment:74)
[Error] Refused to execute https://raw.githubusercontent.com/drvic10k/bootstrap-sortable/1.11.2/Scripts/bootstrap-sortable.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
[Log] session Storage available (v_171_ca7e46e409c988aeda5f1cefb5d3429d.js, line 306)
[Error] IntegrationError: Live Stripe.js integrations must use HTTPS. For more information: https://stripe.com/docs/security/guide#tls
	value (v3:1:392916)
	e (v3:1:355825)
	gc (v3:1:394193)
	initStripe (eupayment:613)

**Comment by DXXS** [comment]
![StripeOnOtherStore](https://github.com/thirtybees/stripe/assets/1892315/52c38ac4-2495-449a-871f-f13b0fbc3624)

**Comment by DXXS** [comment]
FWIW, it looks like the Stripe 'WebHook' for the main store is showing an https:// URL, while the multistore variants are just showing http://

The 'multistore' configurator apparently just builds ineditible http:// variants for all of the stores, including the main one.

**Comment by getdatakick** [comment]
Do you have enabled SSL for all your stores?

**Comment by DXXS** [comment]
'Enable SSL' is turned on in Preferences > General, but it doesn't have a per-multistore option!?

**Comment by DXXS** [comment]
Hmm... If I am accessing the site via https, and then go to the 'check out' button, it apparently switches to http for some reason when bringing up the 'quick-order' url.  If I force it back to https there, it does appear to more appropriately go through to the more appropriate checkout.stripe.com page... (!?)  I guess I could force apache to use SSL all the time, though I'm not sure I should have to...

**Comment by DXXS** [comment]
Ahh... in switching to the store itself, and bringing up the 'general' preferences, the multistore selector became available, and 'SSL' was apparently indeed somehow not explicitly enabled... in enabling, the stripe behavior now seems to be working!

I do think that a more useful ~error display (or SSL 'all shops' enablement conflict indicator) or other feedback might make things more clear!

Thanks for your assistance!

**Comment by getdatakick** [comment]
I agree. I've created issue #71 to display warnings in module back office config page (and in front office when we detect non https:// access)
