### ISSUE TITLE
No 'vendor/autoload.php 'and 'StripeModule\StripeApi' Class not found

### ISSUE THREAD

**Issue by ME-HK** [thirtybees/stripe#72]
Hi, please help!

I don't know why, but downloading the module [master] is different from Assets [stripe-v1.8.2.zip] (https://github.com/thirtybees/stripe/releases/download/1.8.2/stripe-v1.8.2.zip)  
  >>> e.g. Does not include WeChat payment.

Since I couldn't upload the module [master] directly from 'Modules and Services', I uploaded it manually via FTP. But after that I ran into some issues:

1) Error log (1): Failed opening required '/home/***/modules/stripe/vendor/autoload.php'   
   >>> The error disappeared after I edited:
      if ( is_readable( __DIR__ . '/vendor/autoload.php' ) ) {
          require_once __DIR__ . '/vendor/autoload.php';
      }

2）Error log (2): Class "StripeModule\StripeApi" not found (Location: modules/stripe/stripe.php line 140)

3) I also tried to copying the folder 'vendor' from [stripe-v1.8.2.zip] to [master], and these errors disappeared. But the checkout link doesn't work and the stripe credit card form cannot be initialized.

Thanks in advance!

**Comment by getdatakick** [comment]
If you want to use code from `master` branch, you need execute `composer install` command to install vendor dependencies.

I have released new version `1.9.0` of the module that contains all recent changes. You can download and use that one. Or you can update stripe module directly from your back office modules page.

**Comment by ME-HK** [comment]
Thank you so much!

Since there was an error in the direct upgrade of BO, I downloaded it from GitHub and it worked perfectly as expected!

Error screenshot for your reference:


￼
