### ISSUE TITLE
Card data fields are not loaded

### ISSUE THREAD

**Issue by Yabbertb** [thirtybees/stripe#73]
In OPC order mode, when customer logs in, the card data fields are not loaded. Only after refreshing page are these fields loaded.
Module version: 1.9.0
![Screenshot_20240406_034811](https://github.com/thirtybees/stripe/assets/144372521/6359b033-b2dd-446d-b939-836fb59c3af6)

**Comment by getdatakick** [comment]
Fixed by 3dd033a8765fae7b72e30f551c944073e9572c4b.

New version of module released
